// tests/parity/corpus.uc — fixture sections covering every emit feature combo.
// Each section mirrors what cur.foreach yields: scalars are strings, list
// fields are arrays. `.name` is the tag; inbounds also set `protocol`.
return [
    { name: "trojan_out_min", kind: "outbound", type: "trojan",
      section: { ".name": "t1", server: "ex.com", server_port: "443", server_password: "p" } },
    { name: "trojan_out_tls_reality", kind: "outbound", type: "trojan",
      section: { ".name": "t2", server: "ex.com", server_port: "443", server_password: "p",
                 tls_enabled: "1", tls_server_name: "sni", tls_insecure: "1",
                 tls_alpn: ["h2","http/1.1"], tls_min_version: "1.2", tls_max_version: "1.3",
                 tls_cipher_suites: ["TLS_AES_128_GCM_SHA256"],
                 reality_enabled: "1", reality_public_key: "PUB", reality_short_id: "ab12" } },
    { name: "trojan_out_utls_ech_frag", kind: "outbound", type: "trojan",
      section: { ".name": "t3", server: "ex.com", server_port: "443", server_password: "p",
                 tls_enabled: "1", utls_enabled: "1", utls_fingerprint: "firefox",
                 tls_ech_enabled: "1", tls_ech_config: ["A","B"], tls_ech_config_path: "/e",
                 tls_fragment: "1", tls_fragment_fallback_delay: "500ms", tls_record_fragment: "1" } },
    { name: "trojan_out_ws", kind: "outbound", type: "trojan",
      section: { ".name": "t4", server: "ex.com", server_port: "443", server_password: "p",
                 transport_type: "ws", transport_path: "/ws", transport_host: "h.com" } },
    { name: "trojan_out_grpc_mux", kind: "outbound", type: "trojan",
      section: { ".name": "t5", server: "ex.com", server_port: "443", server_password: "p",
                 transport_type: "grpc", transport_service_name: "Svc",
                 multiplex_enabled: "1", multiplex_protocol: "yamux",
                 multiplex_max_connections: "4", multiplex_padding: "1" } },
    { name: "trojan_out_httpupgrade", kind: "outbound", type: "trojan",
      section: { ".name": "t7", server: "ex.com", server_port: "443", server_password: "p",
                 transport_type: "httpupgrade", transport_path: "/hu", transport_host_httpupgrade: "hu.com" } },
    { name: "trojan_out_xhttp", kind: "outbound", type: "trojan",
      section: { ".name": "t8", server: "ex.com", server_port: "443", server_password: "p",
                 transport_type: "xhttp", transport_path: "/x", transport_xhttp_mode: "stream-up" } },
    { name: "trojan_out_http", kind: "outbound", type: "trojan",
      section: { ".name": "t9", server: "ex.com", server_port: "443", server_password: "p",
                 transport_type: "http", transport_hosts: ["a.com","b.com"], transport_path: "/h" } },
    { name: "trojan_out_dial", kind: "outbound", type: "trojan",
      section: { ".name": "t6", server: "ex.com", server_port: "443", server_password: "p",
                 bind_interface: "eth0", routing_mark: "100", connect_timeout: "5s",
                 tcp_fast_open: "1", udp_fragment: "1", detour: "other", domain_strategy: "ipv4_only" } },
    { name: "trojan_out_mux_brutal", kind: "outbound", type: "trojan",
      section: { ".name": "tb1", server: "ex.com", server_port: "443", server_password: "p",
                 multiplex_enabled: "1", multiplex_protocol: "smux",
                 brutal_enabled: "1", brutal_up_mbps: "100", brutal_down_mbps: "50" } },
    { name: "direct_out_empty", kind: "outbound", type: "direct",
      section: { ".name": "d1" } },
    { name: "direct_out_full", kind: "outbound", type: "direct",
      section: { ".name": "d2", override_address: "1.1.1.1", override_port: "5353", proxy_protocol: "2" } },
    { name: "vless_out_min", kind: "outbound", type: "vless",
      section: { ".name": "v1", server: "ex.com", server_port: "443", server_uuid: "11111111-1111-1111-1111-111111111111" } },
    { name: "vless_out_flow_udp", kind: "outbound", type: "vless",
      section: { ".name": "v2", server: "ex.com", server_port: "443", server_uuid: "uuid-x",
                 vless_flow: "xtls-rprx-vision", network: "udp", packet_encoding: "xudp" } },
    { name: "vless_out_net_tcp_skip", kind: "outbound", type: "vless",
      section: { ".name": "v3", server: "ex.com", server_port: "443", server_uuid: "uuid-x",
                 network: "tcp", packet_encoding: "xudp" } },
    { name: "ss_out_min", kind: "outbound", type: "shadowsocks",
      section: { ".name": "s1", server: "ex.com", server_port: "8388",
                 shadowsocks_method: "2022-blake3-aes-128-gcm", server_password: "pw" } },
    { name: "ss_out_plugin", kind: "outbound", type: "shadowsocks",
      section: { ".name": "s2", server: "ex.com", server_port: "8388",
                 shadowsocks_method: "aes-256-gcm", server_password: "pw",
                 plugin: "v2ray-plugin", plugin_opts: "tls;host=x", network: "udp", udp_over_tcp: "1" } },
    { name: "ss_out_plugin_opts_no_plugin", kind: "outbound", type: "shadowsocks",
      section: { ".name": "s3", server: "ex.com", server_port: "8388",
                 shadowsocks_method: "aes-256-gcm", server_password: "pw",
                 plugin_opts: "orphaned" } },
    { name: "hy2_out_min", kind: "outbound", type: "hysteria2",
      section: { ".name": "h1", server: "ex.com", server_port: "443", server_password: "pw" } },
    { name: "hy2_out_obfs_net", kind: "outbound", type: "hysteria2",
      section: { ".name": "h2", server: "ex.com", server_port: "443", server_password: "pw",
                 obfs_type: "salamander", obfs_password: "op", up_mbps: "50", down_mbps: "200",
                 masquerade: "https://x", brutal_debug: "1", network: "udp" } },
    { name: "hy2_out_obfs_partial", kind: "outbound", type: "hysteria2",
      section: { ".name": "h3", server: "ex.com", server_port: "443", server_password: "pw",
                 obfs_type: "salamander" } },
    { name: "hy2_out_force_tls", kind: "outbound", type: "hysteria2",
      section: { ".name": "hf", server: "ex.com", server_port: "443", server_password: "pw" } },
    { name: "mixed_in_nouser", kind: "inbound", type: "mixed",
      section: { ".name": "m1", protocol: "mixed", listen_port: "1080" } },
    { name: "mixed_in_users", kind: "inbound", type: "mixed",
      section: { ".name": "m2", protocol: "mixed", listen: "127.0.0.1", listen_port: "1080",
                 mixed_user: ["alice:secret","bob:pa:ss"] } },
    { name: "tproxy_in", kind: "inbound", type: "tproxy",
      section: { ".name": "tp1", protocol: "tproxy", listen_port: "7895", network: "tcp",
                 tcp_fast_open: "1", udp_fragment: "1",
                 interface: ["br-lan"], nft_rules: "1", hijack_dns: "1" } },
    { name: "direct_in", kind: "inbound", type: "direct",
      section: { ".name": "di1", protocol: "direct", listen_port: "5353", network: "udp",
                 override_address: "1.1.1.1", override_port: "53", tcp_fast_open: "1", udp_fragment: "1" } },
    { name: "trojan_in", kind: "inbound", type: "trojan",
      section: { ".name": "ti1", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", tls_server_name: "sni", transport_type: "ws", transport_path: "/w" } },
    { name: "trojan_in_reality", kind: "inbound", type: "trojan",
      section: { ".name": "tir", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", reality_enabled: "1", reality_private_key: "PRIV",
                 reality_short_id: "ab12", reality_handshake_server: "ex.com",
                 reality_handshake_server_port: "443", tls_ech_enabled: "1", tls_ech_key: ["K"] } },
    { name: "vless_in_single", kind: "inbound", type: "vless",
      section: { ".name": "vi1", protocol: "vless", listen_port: "443",
                 server_uuid: "11111111-1111-1111-1111-111111111111", vless_flow: "xtls-rprx-vision",
                 tls_enabled: "1" } },
    { name: "vless_in_multi", kind: "inbound", type: "vless",
      section: { ".name": "vi2", protocol: "vless", listen_port: "443",
                 inbound_user: ["alice:uuid-a:xtls-rprx-vision","bob:uuid-b","bad: ","carol:uuid c"] } },
    { name: "ss_in_single", kind: "inbound", type: "shadowsocks",
      section: { ".name": "si1", protocol: "shadowsocks", listen_port: "8388",
                 shadowsocks_method: "2022-blake3-aes-128-gcm", server_password: "pw", network: "tcp" } },
    { name: "ss_in_multi", kind: "inbound", type: "shadowsocks",
      section: { ".name": "si2", protocol: "shadowsocks", listen_port: "8388",
                 shadowsocks_method: "2022-blake3-aes-128-gcm", server_password: "pw",
                 ss_user: ["alice:aes-256-gcm:base64pw","bad:nomethod","eve:aes-256-gcm:"] } },
    { name: "hy2_in_single", kind: "inbound", type: "hysteria2",
      section: { ".name": "hi1", protocol: "hysteria2", listen_port: "443", server_password: "pw",
                 up_mbps: "50", down_mbps: "200", obfs_type: "salamander", obfs_password: "op",
                 brutal_debug: "1", ignore_client_bandwidth: "1" } },
    { name: "hy2_in_multi", kind: "inbound", type: "hysteria2",
      section: { ".name": "hi2", protocol: "hysteria2", listen_port: "443",
                 inbound_user: ["alice:pw1","bob:pw:2"] } },
    { name: "hy2_in_users_obfs", kind: "inbound", type: "hysteria2",
      section: { ".name": "hio", protocol: "hysteria2", listen_port: "443",
                 inbound_user: ["alice:pw1","bob:pw:2"],
                 obfs_type: "salamander", obfs_password: "op",
                 up_mbps: "50", down_mbps: "200", masquerade: "https://m",
                 brutal_debug: "1", ignore_client_bandwidth: "1" } },
    { name: "trojan_in_reality_server_only", kind: "inbound", type: "trojan",
      section: { ".name": "tirs", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", reality_enabled: "1", reality_private_key: "PRIV",
                 reality_short_id: "ab12", reality_handshake_server: "ex.com" } },
    { name: "trojan_in_reality_port_only", kind: "inbound", type: "trojan",
      section: { ".name": "tirp", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", reality_enabled: "1", reality_private_key: "PRIV",
                 reality_short_id: "ab12", reality_handshake_server_port: "8443" } },
    { name: "trojan_in_ech_keypath", kind: "inbound", type: "trojan",
      section: { ".name": "tiek", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", tls_ech_enabled: "1", tls_ech_key_path: "/etc/ech.key" } },
    { name: "trojan_in_certpaths", kind: "inbound", type: "trojan",
      section: { ".name": "tic", protocol: "trojan", listen_port: "443", server_password: "pw",
                 tls_enabled: "1", tls_certificate_path: "/etc/cert.pem", tls_key_path: "/etc/key.pem" } },
    { name: "hy2_out_network_bogus", kind: "outbound", type: "hysteria2",
      section: { ".name": "hnb", server: "ex.com", server_port: "443", server_password: "pw", network: "sctp" } },
    { name: "tproxy_in_network_bogus", kind: "inbound", type: "tproxy",
      section: { ".name": "tnb", protocol: "tproxy", listen_port: "7895", network: "sctp" } },
    { name: "socks_out_min", kind: "outbound", type: "socks",
      section: { ".name": "sk1", server: "ex.com", server_port: "1080" } },
    { name: "socks_out_auth", kind: "outbound", type: "socks",
      section: { ".name": "sk2", server: "ex.com", server_port: "1080",
                 socks_version: "5", username: "u", server_password: "p", network: "udp", udp_over_tcp: "1" } },
    { name: "socks_in_users", kind: "inbound", type: "socks",
      section: { ".name": "sk_in", protocol: "socks", listen_port: "1080",
                 socks_user: ["alice:secret", "bob:pw"] } },
    { name: "http_out_tls", kind: "outbound", type: "http",
      section: { ".name": "h_out", server: "ex.com", server_port: "8080",
                 username: "u", server_password: "p", http_path: "/proxy",
                 tls_enabled: "1", tls_server_name: "ex.com" } },
    { name: "http_in_users", kind: "inbound", type: "http",
      section: { ".name": "h_in", protocol: "http", listen_port: "8080",
                 http_user: ["alice:secret"] } },
    { name: "vmess_out_min", kind: "outbound", type: "vmess",
      section: { ".name": "vm1", server: "ex.com", server_port: "443",
                 server_uuid: "bf000d23-0752-40b4-affe-68f7707a9661" } },
    { name: "vmess_out_full", kind: "outbound", type: "vmess",
      section: { ".name": "vm2", server: "ex.com", server_port: "443",
                 server_uuid: "bf000d23-0752-40b4-affe-68f7707a9661",
                 vmess_security: "aes-128-gcm", alter_id: "0", global_padding: "1",
                 authenticated_length: "1", network: "tcp", packet_encoding: "xudp",
                 transport_type: "ws", transport_path: "/vm", multiplex_enabled: "1" } },
    { name: "vmess_in_users", kind: "inbound", type: "vmess",
      section: { ".name": "vm_in", protocol: "vmess", listen_port: "443",
                 vmess_user: ["alice:11111111-1111-1111-1111-111111111111"],
                 tls_enabled: "1", tls_certificate_path: "/c.pem", tls_key_path: "/k.pem" } },
    { name: "hysteria_out", kind: "outbound", type: "hysteria",
      section: { ".name": "hy1", server: "ex.com", server_port: "443",
                 up_mbps: "100", down_mbps: "100", hysteria_auth_str: "secret",
                 obfs: "xplus", server_ports: ["2080:3000"], hop_interval: "30s",
                 quic_initial_packet_size: "1200",
                 tls_server_name: "ex.com" } },
    { name: "hysteria_in", kind: "inbound", type: "hysteria",
      section: { ".name": "hy_in", protocol: "hysteria", listen_port: "443",
                 up_mbps: "100", down_mbps: "200", hysteria_user: ["alice:secret"],
                 tls_certificate_path: "/c.pem", tls_key_path: "/k.pem" } },
    { name: "tuic_out", kind: "outbound", type: "tuic",
      section: { ".name": "tu1", server: "ex.com", server_port: "443",
                 server_uuid: "2DD61D93-75D8-4DA4-AC0E-6AECE7EAC365", server_password: "hello",
                 congestion_control: "bbr", udp_relay_mode: "native", zero_rtt_handshake: "1",
                 heartbeat: "10s", tls_server_name: "ex.com" } },
    { name: "tuic_in", kind: "inbound", type: "tuic",
      section: { ".name": "tu_in", protocol: "tuic", listen_port: "443",
                 tuic_user: ["alice:059032A9-7D40-4A96-9BB1-36823D848068:hello"],
                 congestion_control: "cubic", auth_timeout: "3s",
                 tls_certificate_path: "/c.pem", tls_key_path: "/k.pem" } },
    { name: "anytls_out", kind: "outbound", type: "anytls",
      section: { ".name": "at1", server: "ex.com", server_port: "443", server_password: "pw",
                 idle_session_timeout: "30s", min_idle_session: "5", tls_server_name: "ex.com" } },
    { name: "anytls_in", kind: "inbound", type: "anytls",
      section: { ".name": "at_in", protocol: "anytls", listen_port: "443",
                 anytls_user: ["alice:secret"], padding_scheme: ["stop=8"],
                 tls_certificate_path: "/c.pem", tls_key_path: "/k.pem" } },
    { name: "shadowtls_out", kind: "outbound", type: "shadowtls",
      section: { ".name": "st1", server: "ex.com", server_port: "443",
                 shadowtls_version: "3", server_password: "pw", tls_server_name: "google.com" } },
    { name: "shadowtls_in", kind: "inbound", type: "shadowtls",
      section: { ".name": "st_in", protocol: "shadowtls", listen_port: "443",
                 shadowtls_version: "3", shadowtls_user: ["alice:secret"],
                 handshake_server: "google.com", handshake_server_port: "443",
                 strict_mode: "1", wildcard_sni: "all" } },
    { name: "ssh_out", kind: "outbound", type: "ssh",
      section: { ".name": "ssh1", server: "ex.com", server_port: "22",
                 ssh_user: "root", server_password: "admin",
                 host_key: ["ssh-ed25519 AAAA..."], client_version: "SSH-2.0-OpenSSH_7.4p1" } },
    { name: "naive_out", kind: "outbound", type: "naive",
      section: { ".name": "nv1", server: "ex.com", server_port: "443",
                 username: "u", server_password: "p", tls_server_name: "ex.com" } },
    { name: "naive_in", kind: "inbound", type: "naive",
      section: { ".name": "nv_in", protocol: "naive", listen_port: "443", network: "udp",
                 naive_user: ["alice:secret"],
                 tls_certificate_path: "/c.pem", tls_key_path: "/k.pem" } },
    { name: "redirect_in", kind: "inbound", type: "redirect",
      section: { ".name": "rd_in", protocol: "redirect", listen_port: "7894" } },
    { name: "cloudflared_in", kind: "inbound", type: "cloudflared",
      section: { ".name": "cf_in", protocol: "cloudflared", token: "eyToken",
                 cf_protocol: "quic", ha_connections: "4", post_quantum: "1" } },
    { name: "selector_out", kind: "outbound", type: "selector",
      section: { ".name": "sel1", group_outbounds: ["proxy-a", "proxy-b", "sub__0"],
                 group_default: "proxy-a", interrupt_exist_connections: "1" } },
    { name: "urltest_out", kind: "outbound", type: "urltest",
      section: { ".name": "ut1", group_outbounds: ["proxy-a", "proxy-b"],
                 group_url: "https://www.gstatic.com/generate_204",
                 group_interval: "3m", group_tolerance: "50" } },
    { name: "ssh_out_full", kind: "outbound", type: "ssh",
      section: { ".name": "ssh2", server: "ex.com", server_port: "22",
                 ssh_user: "root", server_password: "admin",
                 private_key_path: "/etc/ssh/id_ed25519",
                 private_key_passphrase: "phrase",
                 host_key_algorithms: ["ssh-ed25519"],
                 ssh_cipher: ["aes256-gcm@openssh.com"],
                 ssh_mac: ["hmac-sha2-256"],
                 ssh_kex_algorithm: ["curve25519-sha256"] } },
    { name: "trojan_out_dial_bind", kind: "outbound", type: "trojan",
      section: { ".name": "tdb", server: "ex.com", server_port: "443", server_password: "p",
                 inet4_bind_address: "10.0.0.2", inet6_bind_address: "fd00::2",
                 netns: "/var/run/netns/vpn", reuse_addr: "1", tcp_multi_path: "1",
                 network_strategy: "fallback", fallback_delay: "300ms" } },
    { name: "trojan_out_mux_streams", kind: "outbound", type: "trojan",
      section: { ".name": "tms", server: "ex.com", server_port: "443", server_password: "p",
                 multiplex_enabled: "1", multiplex_protocol: "yamux",
                 multiplex_min_streams: "4", multiplex_max_streams: "16" } },
    { name: "hy2_out_quic114", kind: "outbound", type: "hysteria2",
      section: { ".name": "hq", server: "ex.com", server_port: "443", server_password: "pw",
                 quic_initial_packet_size: "1280", quic_disable_path_mtu_discovery: "1" } },
    { name: "hysteria_out_recv", kind: "outbound", type: "hysteria",
      section: { ".name": "hyr", server: "ex.com", server_port: "443",
                 up_mbps: "100", down_mbps: "100", hysteria_auth_str: "secret",
                 recv_window: "8388608", recv_window_conn: "4194304",
                 quic_disable_path_mtu_discovery: "1",
                 tls_server_name: "ex.com" } },
    { name: "urltest_out_full", kind: "outbound", type: "urltest",
      section: { ".name": "utf", group_outbounds: ["proxy-a", "proxy-b"],
                 group_url: "https://www.gstatic.com/generate_204",
                 group_interval: "3m", group_tolerance: "50",
                 group_idle_timeout: "30m", interrupt_exist_connections: "1" } },
];
