#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034
USE_PROCD=1
START=99
STOP=01

GENERATE_UC=/usr/share/singbox-ui/generate.uc
NFTABLES_SH=/etc/singbox-ui/nftables.sh

start_service() {
	ucode "$GENERATE_UC"
	[ "$(uci -q get singbox-ui.tproxy.enabled)" = "1" ] && \
		"$NFTABLES_SH" apply

	procd_open_instance
	procd_set_param command /usr/bin/sing-box run -c /tmp/singbox-ui.json
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	"$NFTABLES_SH" remove
}

reload_config() {
	# sing-box does not support signal-based config reload.
	stop
	start
}
