#!/bin/sh
# scripts/gen-manifest.sh
# Auto-generate scripts/install-manifest.txt by scanning luci-app-singbox-ui/.
# Mode detection: anything under etc/init.d/, etc/uci-defaults/, or
# usr/libexec/rpcd/ is 'bin'; etc/config/ is 'conf'; everything else 'data'.
# Manual overrides in scripts/install-manifest-overrides.txt (TSV same shape).
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG="$ROOT/luci-app-singbox-ui"
OUT="$ROOT/scripts/install-manifest.txt"
OVERRIDES="$ROOT/scripts/install-manifest-overrides.txt"

mode_for() {
	case "$1" in
		root/etc/init.d/*|root/etc/uci-defaults/*|root/usr/libexec/rpcd/*) echo bin ;;
		root/etc/config/*) echo conf ;;
		*) echo data ;;
	esac
}

dst_for() {
	case "$1" in
		root/*)    echo "${1#root/}" ;;
		htdocs/*)  echo "www/${1#htdocs/}" ;;
		*)         echo "$1" ;;
	esac
}

{
	echo "# Auto-generated by scripts/gen-manifest.sh. Do not edit by hand."
	echo "# Overrides: scripts/install-manifest-overrides.txt"
	printf '# Format: <src>\\t<dst>\\t<mode>\n'
	cd "$PKG"
	# root + htdocs trees. Exclude po/templates and po/ru (handled separately
	# by the po2lmo install step in Makefile).
	find root htdocs -type f 2>/dev/null | sort | while read -r src; do
		# Apply override if present
		if [ -f "$OVERRIDES" ] && grep -q "^$src	" "$OVERRIDES"; then
			grep "^$src	" "$OVERRIDES"
			continue
		fi
		mode=$(mode_for "$src")
		dst=$(dst_for "$src")
		printf '%s\t%s\t%s\n' "$src" "$dst" "$mode"
	done
} > "$OUT"

echo "Wrote $OUT" >&2
