#!/bin/sh
# scripts/gen-manifest.sh
# Auto-generate the per-package install manifests by scanning each package dir.
# Two packages carry installable file trees:
#   singbox-ui/          -> scripts/install-manifest-singbox-ui.txt
#   luci-app-singbox-ui/ -> scripts/install-manifest-luci-app-singbox-ui.txt
# (bbolt-client ships a single prebuilt binary embedded by build-apk.sh — no
#  manifest. i18n .po/.pot under luci-app-singbox-ui/po are handled by the
#  po2lmo step in the Makefile / build-apk, not the manifest.)
# Mode detection: anything under etc/init.d/, etc/uci-defaults/, or
# usr/libexec/rpcd/ is 'bin'; etc/config/ is 'conf'; everything else 'data'.
# Manual overrides in scripts/install-manifest-overrides.txt (TSV same shape).
set -e

ROOT="${ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OVERRIDES="${OVERRIDES:-$ROOT/scripts/install-manifest-overrides.txt}"

mode_for() {
	case "$1" in
		root/etc/init.d/*|root/etc/uci-defaults/*|root/usr/libexec/rpcd/*) echo bin ;;
		root/etc/config/*) echo conf ;;
		*) echo data ;;
	esac
}

dst_for() {
	case "$1" in
		root/*)    echo "${1#root/}" ;;
		htdocs/*)  echo "www/${1#htdocs/}" ;;
		*)         echo "$1" ;;
	esac
}

# gen_one <pkg-dir> <out-manifest>
# Scans <pkg-dir>/{root,htdocs} and writes the TSV manifest. Both args may be
# absolute or relative to ROOT (the test seam passes absolute throwaway paths).
# The cd is contained in a subshell so successive calls don't leak the CWD.
gen_one() {
	gen_pkg="$1"; gen_out="$2"
	case "$gen_pkg" in /*) gen_pkg_abs="$gen_pkg" ;; *) gen_pkg_abs="$ROOT/$gen_pkg" ;; esac
	case "$gen_out" in /*) gen_out_abs="$gen_out" ;; *) gen_out_abs="$ROOT/$gen_out" ;; esac
	(
		echo "# Auto-generated by scripts/gen-manifest.sh. Do not edit by hand."
		echo "# Overrides: scripts/install-manifest-overrides.txt"
		printf '# Format: <src>\\t<dst>\\t<mode>\n'
		cd "$gen_pkg_abs"
		# root + htdocs trees. po/ (templates + ru) is excluded — handled by the
		# po2lmo install step. LC_ALL=C: deterministic byte-order sort regardless
		# of the caller's locale (host/CI/VM agree; see test_install_manifest_fresh).
		find root htdocs -type f 2>/dev/null | LC_ALL=C sort | while read -r src; do
			# Apply override if present. Match the source column as a FIXED string
			# on the first TAB-separated field — never as a regex.
			ovr=""
			if [ -f "$OVERRIDES" ]; then
				ovr=$(awk -F '\t' -v s="$src" '$1 == s { print; exit }' "$OVERRIDES")
			fi
			if [ -n "$ovr" ]; then
				printf '%s\n' "$ovr"
				continue
			fi
			printf '%s\t%s\t%s\n' "$src" "$(dst_for "$src")" "$(mode_for "$src")"
		done
	) > "$gen_out_abs"
	echo "Wrote $gen_out_abs" >&2
}

# Test seam: an explicit single PKG+OUT pair drives gen_one against a throwaway
# tree (the S5-8 exact-match override regression in test_gen_manifest_override).
# Production: no PKG/OUT set -> emit both per-package manifests.
if [ -n "${PKG:-}" ] && [ -n "${OUT:-}" ]; then
	gen_one "$PKG" "$OUT"
else
	gen_one singbox-ui          scripts/install-manifest-singbox-ui.txt
	gen_one luci-app-singbox-ui scripts/install-manifest-luci-app-singbox-ui.txt
fi
