#!/bin/sh
# scripts/gen-manifest.sh
# Auto-generate scripts/install-manifest.txt by scanning luci-singbox-ui/.
# Mode detection: anything under etc/init.d/, etc/uci-defaults/, or
# usr/libexec/rpcd/ is 'bin'; etc/config/ is 'conf'; everything else 'data'.
# Manual overrides in scripts/install-manifest-overrides.txt (TSV same shape).
set -e

ROOT="${ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PKG="${PKG:-$ROOT/luci-singbox-ui}"
OUT="${OUT:-$ROOT/scripts/install-manifest.txt}"
OVERRIDES="${OVERRIDES:-$ROOT/scripts/install-manifest-overrides.txt}"

mode_for() {
	case "$1" in
		root/etc/init.d/*|root/etc/uci-defaults/*|root/usr/libexec/rpcd/*) echo bin ;;
		root/etc/config/*) echo conf ;;
		*) echo data ;;
	esac
}

dst_for() {
	case "$1" in
		root/*)    echo "${1#root/}" ;;
		htdocs/*)  echo "www/${1#htdocs/}" ;;
		*)         echo "$1" ;;
	esac
}

{
	echo "# Auto-generated by scripts/gen-manifest.sh. Do not edit by hand."
	echo "# Overrides: scripts/install-manifest-overrides.txt"
	printf '# Format: <src>\\t<dst>\\t<mode>\n'
	cd "$PKG"
	# root + htdocs trees. Exclude po/templates and po/ru (handled separately
	# by the po2lmo install step in Makefile).
	# LC_ALL=C: deterministic byte-order sort regardless of the caller's locale.
	# The OpenWrt VM (BusyBox sort) and a default host both collate in C order; a
	# runner with en_US.UTF-8 would otherwise produce a different order and make
	# test_install_manifest_fresh fail only in the VM. Pin it so host/CI/VM agree.
	find root htdocs -type f 2>/dev/null | LC_ALL=C sort | while read -r src; do
		# Apply override if present. Match the source column as a FIXED
		# string on the first TAB-separated field — never as a regex —
		# so path metacharacters (. * [ + …) can't false-match another
		# override row. (Was `grep "^$src\t"`, which treats $src as a
		# regex; see spec S5-8.)
		ovr=""
		if [ -f "$OVERRIDES" ]; then
			ovr=$(awk -F '\t' -v s="$src" '$1 == s { print; exit }' "$OVERRIDES")
		fi
		if [ -n "$ovr" ]; then
			printf '%s\n' "$ovr"
			continue
		fi
		mode=$(mode_for "$src")
		dst=$(dst_for "$src")
		printf '%s\t%s\t%s\n' "$src" "$dst" "$mode"
	done
} > "$OUT"

echo "Wrote $OUT" >&2
